In [3]:
import numpy as np
import tensorflow as tf

In [4]:
inputs = np.array([[73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], [69, 96, 70],[73, 67, 43], [91, 88, 64], 
                   [87, 134, 58], [102, 43, 37], [69, 96, 70], [73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], 
                   [69, 96, 70]], dtype='float64')

targets = np.array([[56, 70], [81, 101], [119, 133], [22, 37], [103, 119],[56, 70], [81, 101], [119, 133], [22, 37], 
                    [103, 119],[56, 70], [81, 101], [119, 133], [22, 37], [103, 119]], dtype='float64')

In [5]:
inputs = tf.Variable(inputs)
targets = tf.Variable(targets)
print("targets :\n",targets)

targets :
 <tf.Variable 'Variable:0' shape=(15, 2) dtype=float64, numpy=
array([[ 56.,  70.],
       [ 81., 101.],
       [119., 133.],
       [ 22.,  37.],
       [103., 119.],
       [ 56.,  70.],
       [ 81., 101.],
       [119., 133.],
       [ 22.,  37.],
       [103., 119.],
       [ 56.,  70.],
       [ 81., 101.],
       [119., 133.],
       [ 22.,  37.],
       [103., 119.]])>


In [6]:
v = np.random.rand(3,2)
r = np.random.randn(2)
v = tf.Variable(v)
r = tf.Variable(r)

print(v)
print("\n",r)

<tf.Variable 'Variable:0' shape=(3, 2) dtype=float64, numpy=
array([[0.63665438, 0.97361821],
       [0.51990612, 0.53113836],
       [0.88958381, 0.21731638]])>

 <tf.Variable 'Variable:0' shape=(2,) dtype=float64, numpy=array([ 0.44440366, -1.36986595])>


In [7]:
def model(s):
    return s @ v + r

In [8]:
prediction = model(inputs)
print(prediction)

tf.Tensor(
[[120.00598699 114.63513783]
 [161.06505423 147.87781513]
 [177.09661529 167.11180846]
 [120.65371438 128.81884713]
 [156.55540962 132.0112196 ]
 [120.00598699 114.63513783]
 [161.06505423 147.87781513]
 [177.09661529 167.11180846]
 [120.65371438 128.81884713]
 [156.55540962 132.0112196 ]
 [120.00598699 114.63513783]
 [161.06505423 147.87781513]
 [177.09661529 167.11180846]
 [120.65371438 128.81884713]
 [156.55540962 132.0112196 ]], shape=(15, 2), dtype=float64)


In [9]:
def mse(t1,t2):
    return tf.reduce_mean(tf.square(t1 - t2))
print(mse(prediction,targets))

tf.Tensor(4043.6566328503386, shape=(), dtype=float64)


In [10]:
epochs = 40
for epoch_count in range(epochs):
    
    with tf.GradientTape(persistent=True) as t:
        current_loss = mse(targets, model(inputs))

    v1 = t.gradient(current_loss,v)
    r1 = t.gradient(current_loss,r)

    v.assign_sub(1e-4 * v1)
    r.assign_sub(1e-4 * r1)
        
    print(f" \n Epoch count: {epoch_count} \n Loss value: {current_loss.numpy()}")


 
 Epoch count: 0 
 Loss value: 4043.6566328503386
 
 Epoch count: 1 
 Loss value: 2728.7788635057213
 
 Epoch count: 2 
 Loss value: 1882.9683091418833
 
 Epoch count: 3 
 Loss value: 1333.4318901124977
 
 Epoch count: 4 
 Loss value: 971.7245105871523
 
 Epoch count: 5 
 Loss value: 729.6994032262205
 
 Epoch count: 6 
 Loss value: 564.4575497767233
 
 Epoch count: 7 
 Loss value: 448.9275266825819
 
 Epoch count: 8 
 Loss value: 365.9682828238932
 
 Epoch count: 9 
 Loss value: 304.6763415079684
 
 Epoch count: 10 
 Loss value: 258.0725131238905
 
 Epoch count: 11 
 Loss value: 221.65200287963518
 
 Epoch count: 12 
 Loss value: 192.47498732877455
 
 Epoch count: 13 
 Loss value: 168.59559753484487
 
 Epoch count: 14 
 Loss value: 148.7028638422354
 
 Epoch count: 15 
 Loss value: 131.89448737590797
 
 Epoch count: 16 
 Loss value: 117.53390428263033
 
 Epoch count: 17 
 Loss value: 105.15963030090857
 
 Epoch count: 18 
 Loss value: 94.42746323164883
 
 Epoch count: 19 
 Loss value